# -*- coding: utf-8 -*-
"""eaf_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYCvohYebVyaYKAMwG-91tS5o3OXPG-j
"""

!pip install pympi-ling

from pympi import Eaf
import csv

def extract_annotations(eaf_file):
    eaf_obj = Eaf(eaf_file)
    annotations = []

    # Iterate over all tiers
    for tier_name in eaf_obj.get_tier_names():
        tier = eaf_obj.get_annotation_data_for_tier(tier_name)

        # Iterate over all annotations in the tier
        for annotation in tier:
            start_time = annotation[0]
            end_time = annotation[1]
            annotation_text = annotation[2]

            # Append time segment and annotation text to the list
            annotations.append([start_time, end_time, tier_name, annotation_text])

    return annotations

def save_to_csv(annotations, output_file):
    with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Start Time', 'End Time', 'Tier', 'Annotation Text'])
        writer.writerows(annotations)

if __name__ == "__main__":
    eaf_file = "debate_2_১ম বাংলাদেশ টেলিভিশন কলেজ বিতর্ক প্রতিযোগিতা। College Debate 17 5 19.eaf"
    output_csv = "output.csv"

    # Extract annotations from EAF file
    annotations = extract_annotations(eaf_file)

    # Save annotations to CSV file
    save_to_csv(annotations, output_csv)
    print("CSV file has been created successfully.")